Args = --enable-http \
       --enable-https \
       -H:+ReportExceptionStackTraces \
       --initialize-at-build-time=thz.lang.ui \
       --initialize-at-build-time=thz.lang.webview \
       -H:IncludeResources=.*\\.thz.*
